### PR TITLE
Update quotes.js

### PR DESCRIPTION
**Pull request by MojoBoingo**
I've left a comment on every line of code I changed, either updating the author and including at least a link as a reference/source, and maybe a few words if I felt it helpful, or noting it was a duplicate quote. I found 12 quotes an author.

### CODE REVIEW

**Comment by MojoBoingo** [comment]
each duplicate quote has a reference to the line of code hosting the original. There are probably more based on the pattern.

**Comment by seths10** [comment]
remove the comments

**Comment by MojoBoingo** [comment]
Looks like you beat me to it? I'm told you've committed and I can't edit this PR.

**Review by seths10 — CHANGES_REQUESTED** [review]
check to see if there are any other comments I forgot to remove

**Comment by MojoBoingo** [comment]
No sign of my comments or any instances of ``//``, should be good.

**Review by seths10 — APPROVED** [review]

**Pull request merged**
