### PR TITLE
Added 10 new quotes

### PR DESCRIPTION
**Pull request by rx-rz**

### CODE REVIEW

**Comment by seths10** [comment]
Try resolving the conflicts

**Comment by rx-rz** [comment]
merge conflict solved

**Review by seths10 — APPROVED** [review]
Good, This is okay. I will merge it into the main branch soon

**Comment by seths10** [comment]
Please do well to limit your next PR to only 10 quotes, Thanks

**Comment by seths10** [comment]
please star the repo

**Pull request merged**
