### PR TITLE
Added copied to clipboard notification popup

### PR DESCRIPTION
**Pull request by Aravind22**
Sorry didn't ask first.

### CODE REVIEW

**Comment by seths10** [comment]
please can you add a screenshot of the feature here?

**Comment by Aravind22** [comment]
SS

**Comment by Aravind22** [comment]
SS
Adding screenshot

**Comment by seths10** [comment]
That's exactly what I wanted

**Comment by seths10** [comment]
I will merge it after reviewing it

**Comment by seths10** [comment]
Thanks for your contribution. Please don't forget to give the repo a star ⭐. Also, don't forget to follow me, Happy Hacktoberfest!!!

**Comment by seths10** [comment]
Thanks for your contribution. Please don't forget to give the repo a star ⭐. Also, don't forget to follow me, Happy Hacktoberfest!!!

**Pull request merged**
