### PR TITLE
Added ten more quotes

### PR DESCRIPTION
**Pull request by EvaMatz**
Hi, I'd like to add ten more quotes to your generator!

### CODE REVIEW

**Comment by seths10** [comment]
please add your quotes to the quotes.js file in the js folder

**Comment by seths10** [comment]
Thanks for contributing. Please consider giving the repository a star 🌟

**Comment by EvaMatz** [comment]
@seths10 Hey, just letting you know that I added my quotes to the quotes.js file!

**Comment by seths10** [comment]
Thanks for contributing, Please consider giving the repo a star 🌟 and don't forget to follow me

**Pull request merged**
