### PR TITLE
Added Quote Category selection option .

### PR DESCRIPTION
**Pull request by jainAashay**
image

--> Choose category wise to view the quote.
--> No need to use quote.js file as a simple api has been used for this purpose.

### CODE REVIEW

**Comment by seths10** [comment]
This is a useful feature, but I want others to be able to contribute to the repo, and using an API will not help with that.

**Comment by seths10** [comment]
If you have the time, you can create a category.js file that contains quotes from different categories. When a category is selected, only quotes from that object (category) are displayed.

**Comment by jainAashay** [comment]
> This is a useful feature, but I want others to be able to contribute to the repo, and using an API will not help with that.

Well that's your wish.
But a website is not meant to contain all the required data in itself whenever it's called.It just create unnecessary burden on the website and also slows it down due to which APIs must be used in such cases.

**Comment by jainAashay** [comment]
> If you have the time, you can create a category.js file that contains quotes from different categories. When a category is selected, only quotes from that object (category) are displayed.

Sure I will do so if I can😊

**Pull request closed without merging**
